Repository PaletteProject/palette, pull requests merged in 2024-11, with the labels that each got.

#51 refactor: update file import ui
  frontend/src/components/rubric-builder/CSVUpload.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/components/util/Dialog.tsx
Labels: refactor

#53 chore/update docs and CI workflow
  .github/workflows/all-tests-passing.yml
  .github/workflows/ci-checks.yml
  .github/workflows/eslint-prettier-checks.yml
  .github/workflows/validate-root-dependencies.yml
  README.md
  backend/tsconfig.json
  docker-compose.yml
  frontend/package-lock.json
  frontend/src/Protocol/BackendRequests.ts
  frontend/src/components/rubric-builder/CSVUpload.tsx
  package-lock.json
  package.json
  palette-types/package-lock.json
Labels: refactor, chore

#72 Fix/reponse null type
  frontend/src/hooks/useFetch.ts
  palette-types/src/protocol/PaletteAPIResponse.ts
Labels: bugfix, refactor

#82 Feature/csv export functionality
  frontend/src/components/util/Navbar.tsx
  frontend/src/features/rubricBuilder/CSVExport.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
Labels: feature

#86 Feature/canvas rubrics crud
  backend/jest.config.js
  backend/src/__tests__/canvasAPITests/fetchAPITests.test.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/createRubricAssociationTest.test.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/createRubricTests.test.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/deleteRubricTests.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/getAllRubricsTests.test.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/getRubricTests.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/updateRubricTests.test.ts
  backend/src/__tests__/utils/rubricUtilsTests.test.ts
  backend/src/__tests__/utils/typeGuardTests/isCanvasErrorResponseTest.test.ts
  backend/src/__tests__/utils/typeGuardTests/isPaginatedRubricsList.test.ts
  backend/src/__tests__/utils/typeGuardTests/isRubricObjectHash.test.ts
  backend/src/app.ts
  backend/src/canvasAPI/rubricRequests.ts
  backend/src/controllers/rubricControllers/handleCreateRubric.ts
  backend/src/controllers/rubricControllers/handleCreateRubricAssociation.ts
  backend/src/controllers/rubricControllers/handleGetAllRubrics.ts
  backend/src/controllers/rubricControllers/handleGetRubricById.ts
  backend/src/controllers/rubricControllers/handleUpdateRubric.ts
  backend/src/errors/UnknownCanvasError.ts
  backend/src/middleware/rubricValidationErrorHandler.ts
  backend/src/routes/courseRouter.ts
  backend/src/routes/rubricRouter.ts
  backend/src/routes/wildcardRouter.ts
  backend/src/utils/fetchAPI.ts
  backend/src/utils/rubricUtils.ts
  backend/src/utils/typeGuards.ts
  backend/src/validators/baseParamValidators.ts
  backend/src/validators/rubricValidator.ts
  frontend/src/components/util/Navbar.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
  frontend/src/resources/templates.json
  package-lock.json
  palette-types/src/Template.ts
  palette-types/src/canvasProtocol/CreateRubricAssociationRequest.ts
  palette-types/src/canvasProtocol/CreateRubricAssociationResponse.ts
  palette-types/src/canvasProtocol/CreateRubricRequest.ts
  palette-types/src/canvasProtocol/GetAllRubricsRequest.ts
  palette-types/src/canvasProtocol/GetAllRubricsResponse.ts
  palette-types/src/canvasProtocol/GetRubricRequest.ts
  palette-types/src/canvasTypes/RubricObjectHash.ts
  palette-types/src/index.ts
Labels: feature, bugfix, test

#91 feature: overhaul rubric builder
  .github/workflows/ci-checks.yml
  backend/package.json
  backend/prisma/migrations/20241014153625_init/migration.sql
  backend/prisma/migrations/20241014174656_update_rubric_model/migration.sql
  backend/prisma/migrations/20241018014701_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018014945_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018160001_updated_validation/migration.sql
  backend/prisma/migrations/20241018162153_update/migration.sql
  backend/prisma/migrations/20241025142836_save_rubrics/migration.sql
  backend/prisma/migrations/20241103011024_init/migration.sql
  backend/prisma/migrations/migration_lock.toml
  backend/prisma/schema.prisma
  backend/src/config.ts
  backend/src/middleware/fallbackErrorHandler.ts
  docker-compose.yml
  frontend/package.json
  frontend/src/components/Dialog.tsx
  frontend/src/components/util/Navbar.tsx
  frontend/src/features/grading/GradingView.tsx
  frontend/src/features/rubricBuilder/CriteriaInput.tsx
  frontend/src/features/rubricBuilder/RatingInput.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
  frontend/src/features/rubricBuilder/UpdatedRatingInput.tsx
  frontend/src/index.css
  frontend/src/utils/index.ts
  frontend/src/utils/rubricFactory.ts
  frontend/tailwind.config.js
  package-lock.json
  package.json
  palette-types/package.json
  palette-types/src/DatabaseSafeTypes.js
  palette-types/src/DatabaseSafeTypes.js.map
Labels: feature, refactor

#96 refactor: backend conversions
  backend/src/__tests__/canvasAPITests/rubricsAPI/getAllRubricsTests.test.ts
  backend/src/__tests__/canvasAPITests/rubricsAPI/getRubricTests.ts
  backend/src/__tests__/utils/rubricUtilsTests.test.ts
  backend/src/canvasAPI/courseRequests.ts
  backend/src/canvasAPI/rubricRequests.ts
  backend/src/controllers/rubricController.ts
  backend/src/controllers/rubricControllers/handleCreateRubric.ts
  backend/src/controllers/rubricControllers/handleGetAllRubrics.ts
  backend/src/controllers/rubricControllers/handleGetRubricById.ts
  backend/src/controllers/rubricControllers/handleUpdateRubric.ts
  backend/src/controllers/templateController.ts
  backend/src/routes/courseRouter.ts
  backend/src/utils/rubricUtils.ts
  frontend/src/features/grading/GradingView.tsx
  palette-types/src/types/Assignment.ts
  palette-types/src/types/Criteria.ts
  palette-types/src/types/Rating.ts
  palette-types/src/types/Rubric.ts
Labels: refactor

#113 bugfix: fix an incorrect modal response during rubric submission errors
  backend/src/canvasAPI/courseRequests.ts
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
Labels: bugfix

#114 fix: prevent default form submit
  frontend/src/features/rubricBuilder/CSVExport.tsx
  frontend/src/features/rubricBuilder/RatingInput.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
Labels: bugfix

#122 hotfix: bypass canvas api
  frontend/src/__tests__/coreModelTests/RubricCriterion.test.ts
  frontend/src/__tests__/coreModelTests/RubricRating.test.ts
  frontend/src/components/ActiveAssignmentSelection.tsx
  frontend/src/components/ActiveCourseSelection.tsx
  frontend/src/components/AssignmentSelectionMenu.tsx
  frontend/src/components/CourseSelectionMenu.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/NoAssignmentSelected.tsx
  frontend/src/components/NoCourseSelected.tsx
  frontend/src/features/grading/GradingView.tsx
  frontend/src/features/rubricBuilder/CriteriaInput.tsx
  frontend/src/features/rubricBuilder/RatingInput.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
  frontend/src/utils/rubricFactory.ts
Labels: hotfix

#130 Feature/user settings interactions
  .gitignore
  backend/package.json
  backend/src/__tests__/settingsTests.test.ts
  backend/src/app.ts
  backend/src/config.ts
  backend/src/controllers/rubricController.ts
  backend/src/controllers/userController.ts
  backend/src/middleware/rubricValidationErrorHandler.ts
  backend/src/middleware/validationErrorHandler.ts
  backend/src/routes/courseRouter.ts
  backend/src/routes/userRouter.ts
  backend/src/settings.ts
  backend/src/utils/fetchAPI.ts
  backend/src/utils/paletteResponseFactories.ts
  backend/src/validators/updateUserSettingsValidator.ts
  frontend/src/components/AssignmentSelectionMenu.tsx
  frontend/src/components/LoadingDots.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/SaveButton.tsx
  frontend/src/components/index.ts
  frontend/src/features/Settings/Settings.tsx
  frontend/src/features/grading/GradingView.tsx
  frontend/src/features/rubricBuilder/RubricBuilder.tsx
  frontend/src/main.tsx
  package-lock.json
  palette-types/src/index.ts
  palette-types/src/types/Settings.ts
Labels: feature

#131 feature: submissions dashboard
  .gitignore
  backend/src/canvasAPI/courseRequests.ts
  backend/src/controllers/courseController.ts
  backend/src/controllers/rubricController.ts
  backend/src/controllers/submissionController.ts
  backend/src/controllers/userController.ts
  backend/src/routes/courseRouter.ts
  backend/src/services/courseRequests.ts
  backend/src/services/rubricRequests.ts
  backend/src/services/transformers.ts
  backend/src/settings.ts
  docs/gradeSubmissionWorkflow.md
  frontend/public/check-icon.png
  frontend/public/close-icon.png
  frontend/public/comment-icon.png
  frontend/public/drop-down-arrow.png
  frontend/public/stopwatch.png
  frontend/public/timer-purple.png
  frontend/src/__tests__/uiTests/Home.test.tsx
  frontend/src/__tests__/uiTests/csvUpload.test.tsx
  frontend/src/components/CourseSelectionMenu.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/MainPageTemplate.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/NoAssignmentSelected.tsx
  frontend/src/components/NoCourseSelected.tsx
  frontend/src/components/index.ts
  frontend/src/context/index.ts
  frontend/src/features/grading/AssignmentData.tsx
  frontend/src/features/grading/GradingMain.tsx
  frontend/src/features/grading/GradingView.tsx
  frontend/src/features/grading/GroupSubmissions.tsx
  frontend/src/features/grading/IndividualSubmission.tsx
  frontend/src/features/grading/ProgressBar.tsx
  frontend/src/features/grading/StatusIcons.tsx
  frontend/src/features/grading/SubmissionsDashboard.tsx
  frontend/src/features/grading/seedData.ts
  frontend/src/features/home/Home.tsx
  frontend/src/features/index.ts
  frontend/src/features/rubricBuilder/CSVExport.tsx
  frontend/src/features/rubricBuilder/CSVUpload.tsx
  frontend/src/features/rubricBuilder/CriteriaInput.tsx
  frontend/src/features/rubricBuilder/RatingInput.tsx
  frontend/src/features/rubricBuilder/RubricBuilderMain.tsx
  frontend/src/features/settings/SettingsMain.tsx
  frontend/src/features/user/templates.json
  frontend/src/main.tsx
  frontend/src/utils/constants.ts
  frontend/src/utils/index.ts
  frontend/src/utils/randomColor.ts
  frontend/src/utils/rubricFactory.ts
  frontend/tsconfig.json
  palette-types/src/canvasProtocol/canvasSubmissionResponse.ts
  palette-types/src/canvasTypes/CanvasSubmission.ts
  palette-types/src/index.ts
  palette-types/src/types/GroupedSubmissions.ts
  palette-types/src/types/Submission.ts
Labels: feature

#138 Create initial issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#135 feature: submission validator
  backend/src/routes/courseRouter.ts
  backend/src/validators/paramValidators.ts
  backend/src/validators/rubricValidator.ts
  backend/src/validators/submissionValidator.ts
  package.json
  palette-types/src/canvasTypes/CanvasSubmission.ts
Labels: feature

#178 hotfix: node ci check
  .github/workflows/ci-checks.yml
  backend/src/validateNode.js
  package.json
Labels: hotfix

#184 refactor: ui improvements
  frontend/src/components/ActiveAssignmentSelection.tsx
  frontend/src/components/ActiveCourseSelection.tsx
  frontend/src/components/buttons/SaveButton.tsx
  frontend/src/components/contextSelectors/ActiveAssignmentSelection.tsx
  frontend/src/components/contextSelectors/ActiveCourseSelection.tsx
  frontend/src/components/contextSelectors/ActiveSelectionButton.tsx
  frontend/src/components/contextSelectors/AssignmentSelectionMenu.tsx
  frontend/src/components/contextSelectors/CourseSelectionMenu.tsx
  frontend/src/components/contextSelectors/NoAssignmentSelected.tsx
  frontend/src/components/contextSelectors/NoCourseSelected.tsx
  frontend/src/components/index.ts
  frontend/src/components/layout/Footer.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/MainPageTemplate.tsx
  frontend/src/components/layout/Navbar.tsx
  frontend/src/components/modals/Dialog.tsx
  frontend/src/components/modals/ModalChoiceDialog.tsx
  frontend/src/features/errorPages/NotFoundPage.tsx
  frontend/src/features/index.ts
  frontend/src/features/rubricBuilder/CriteriaInput.tsx
  frontend/src/features/rubricBuilder/RubricBuilderMain.tsx
  frontend/src/main.tsx
  package.json
Labels: refactor
