Repository PaletteProject/palette, pull requests merged in 2024-10, with the labels that each got.

#16 security-fix: update SheetsJS to latest module
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#15 US76: Rubric Data Persistence, API endpoints
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20241018014701_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018014945_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018160001_updated_validation/migration.sql
  backend/prisma/migrations/20241018162153_update/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.js
  backend/src/app.ts
  backend/src/routes/rubricRouter.ts
  backend/src/routes/userRouter.ts
  backend/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/main.tsx
  frontend/src/models/Criteria.ts
  frontend/src/models/Rubric.ts
  frontend/src/models/types/criteria.js
  frontend/src/models/types/criteria.ts
  frontend/src/models/types/rating.js
  frontend/src/models/types/rubric.ts
  frontend/tsconfig.json
Labels: enhancement

#18 Us95 task113
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/rubric-builder/CSVUpload.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/models/Criteria.ts
  frontend/src/models/types/rating.ts
Labels: enhancement

#17 condense criteria display, implement drag and drop functionality
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/rubric-builder/CSVUpload.tsx
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/tailwind.config.js
Labels: enhancement

#20 refactor/add react keys
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/models/Criteria.ts
  frontend/src/models/Rating.ts
  frontend/src/models/Rubric.ts
  frontend/src/models/types/criteria.js
  frontend/src/models/types/criteria.ts
  frontend/src/models/types/rating.js
  frontend/src/models/types/rating.ts
  frontend/src/models/types/rubric.ts
Labels: enhancement

#21 chore/continous integration script
  .github/workflows/eslint-prettier-checks.yml
  backend/.prettierrc
  backend/eslint.config.js
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20241014153625_init/migration.sql
  backend/prisma/migrations/20241014174656_update_rubric_model/migration.sql
  backend/prisma/migrations/20241018014701_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018014945_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018160001_updated_validation/migration.sql
  backend/prisma/migrations/20241018162153_update/migration.sql
  backend/prisma/seed.js
  backend/src/app.ts
  backend/src/routes/rubricRouter.ts
  backend/src/types/models.ts
  backend/tsconfig.json
  frontend/.prettierrc
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/home/Home.tsx
  frontend/src/components/rubric-builder/CSVUpload.tsx
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/components/util/Dialog.tsx
  frontend/src/components/util/Footer.tsx
  frontend/src/components/util/Header.tsx
  frontend/src/components/util/NotFoundPage.tsx
  frontend/src/main.tsx
  frontend/src/models/Criteria.ts
  frontend/src/models/Rating.ts
  frontend/src/models/Rubric.ts
  frontend/src/models/types/criteria.ts
  frontend/src/models/types/rubric.ts
  frontend/tsconfig.json
Labels: enhancement

#23 Bugfix/max points calc
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/models/Criteria.ts
  frontend/src/models/types/criteria.ts
  frontend/src/models/types/rating.ts
Labels: bug

#31 feature: condense rating options
  frontend/src/assets/description-icon.webp
  frontend/src/assets/x-icon2.webp
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/tsconfig.json
Labels: enhancement

#28 Feature/save rubrics
  .gitignore
  README.md
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20241014174656_update_rubric_model/migration.sql
  backend/prisma/migrations/20241018014701_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018162153_update/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.ts
  backend/src/routes/rubricRouter.ts
  backend/src/types/models.ts
  backend/tsconfig.json
  frontend/.prettierrc
  frontend/docker-compose.yml
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Protocol/BackendRequests.ts
  frontend/src/assets/react.svg
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/components/util/ModalChoiceDialog.tsx
  frontend/src/index.css
  frontend/src/models/Rubric.ts
  frontend/src/models/types/Rubric.ts
  frontend/src/models/types/RubricCriterion.ts
  frontend/src/models/types/RubricRating.ts
  frontend/src/models/types/criteria.ts
  frontend/src/models/types/rating.ts
  frontend/src/models/types/rubric.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: enhancement

#30 Long descrip/edit. Create a clickable description of editing long description
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/description-icon.webp
  frontend/src/assets/x-icon2.webp
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/tsconfig.json
Labels: enhancement

#26 chore: initialize palette-types module
  .github/workflows/eslint-prettier-checks.yml
  backend/package-lock.json
  backend/package.json
  frontend/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/index.css
  palette-types/.prettierrc
  palette-types/eslint.config.js
  palette-types/package-lock.json
  palette-types/package.json
  palette-types/src/Criteria.ts
  palette-types/src/Rating.ts
  palette-types/src/Rubrics.ts
  palette-types/src/index.ts
  palette-types/src/protocol.ts
  palette-types/tsconfig.json
Labels: enhancement

#25 Chore/containerize express
  README.md
  backend/Dockerfile
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20241014174656_update_rubric_model/migration.sql
  backend/prisma/migrations/20241018014701_canvas_api_models/migration.sql
  backend/prisma/migrations/20241018162153_update/migration.sql
  backend/prisma/migrations/20241025142836_save_rubrics/migration.sql
  backend/src/routes/rubricRouter.ts
  docker-compose.yml
  frontend/Dockerfile
  frontend/index.html
  frontend/tsconfig.json
  start.sh
Labels: enhancement

#32 Refactor/npm workspace
  .github/workflows/validate-root-dependencies.yml
  README.md
  backend/package.json
  package-lock.json
  package.json
Labels: enhancement

#35 Fix/global npm docker integration
  .github/workflows/eslint-prettier-checks.yml
  Dockerfile
  README.md
  backend/.prettierrc
  backend/Dockerfile
  backend/eslint.config.js
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/routes/rubricRouter.ts
  backend/tsconfig.json
  docker-compose.yml
  eslint.config.js
  frontend/.gitignore
  frontend/.prettierrc
  frontend/Dockerfile
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Protocol/BackendRequests.ts
  frontend/src/components/home/Home.tsx
  frontend/src/components/rubric-builder/CSVUpload.tsx
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/components/util/Dialog.tsx
  frontend/src/components/util/Footer.tsx
  frontend/src/components/util/Header.tsx
  frontend/src/components/util/ModalChoiceDialog.tsx
  frontend/src/components/util/NotFoundPage.tsx
  frontend/src/main.tsx
  frontend/src/models/types/Rubric.ts
  frontend/src/models/types/RubricCriterion.ts
  frontend/src/models/types/RubricRating.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/vite.config.ts
  package-lock.json
  package.json
  palette-types/.prettierrc
  palette-types/eslint.config.js
  palette-types/package.json
  palette-types/src/index.ts
  palette-types/tsconfig.json
  start.sh
Labels: enhancement

#41 test: configure jest for the frontend module
  .gitignore
  backend/package.json
  backend/prisma/schema.prisma
  frontend/jest.config.js
  frontend/package.json
  frontend/src/Protocol/BackendRequests.ts
  frontend/src/__tests__/BackendRequests.test.ts
  frontend/src/__tests__/Rubric.test.ts
  frontend/src/__tests__/RubricCriterion.test.ts
  frontend/src/__tests__/RubricRating.test.ts
  frontend/src/components/rubric-builder/CriteriaInput.tsx
  frontend/src/components/rubric-builder/RatingInput.tsx
  frontend/src/components/rubric-builder/RubricBuilder.tsx
  frontend/src/models/Rubric.ts
  frontend/src/models/RubricCriterion.ts
  frontend/src/models/RubricRating.ts
  frontend/tsconfig.json
  package-lock.json
Labels: enhancement

#33 feature: navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/home/Home.tsx
  frontend/src/components/user/UserClusters.tsx
  frontend/src/components/user/UserRubrics.tsx
  frontend/src/components/util/Footer.tsx
  frontend/src/components/util/Header.tsx
  frontend/src/components/util/Navbar.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  package-lock.json
Labels: feature

#50 Refactor/extract backend interface
  backend/package.json
  backend/src/routes/rubricRouter.ts
  backend/src/services/prismaRubricService.ts
  backend/src/services/rubricService.ts
  backend/src/validators/rubricValidator.ts
  backend/tsconfig.json
  frontend/package.json
  package-lock.json
  palette-types/src/DatabaseSafeTypes.ts
Labels: refactor
